spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/mentalhealth
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:211004}

  jpa:
    hibernate:
      ddl-auto: create-drop

  logging:
    level:
      org.springframework.web: DEBUG
