spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ajax81968@gmail.com
    password: vlxv lrkn kuox xssz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: mental-health
  app:
    jwtSecret: ${JWT_SECRET:8EBUtzmOnBj56DWepYHgxuNv8rJrOYFXkqptcCzW7LVyQUV1mNhrb1UlyP1qebfk}


  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mental_health}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:211004}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

  logging:
    level:
      org.springframework: INFO
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  servlet:
    context-path: /mental-health

management:
  endpoints:
    web:
      exposure:
        include: health,info
mvc:
  throw-exception-if-no-handler-found: true
cloudinary:
  cloud-name: dkadqnp9j
  api-key: 146538996393818
  api-secret: CHvCutfYZe_DTYAjulQB_GOYT7s
  url: cloudinary://146538996393818:CHvCutfYZe_DTYAjulQB_GOYT7s@dkadqnp9j