spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-email-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: mental-health
  app:
    jwtSecret: ${JWT_SECRET:your-jwt-secret}
    jwtExpirationMs: ${JWT_EXPIRATION_MS:3600000}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:your-database-name}
    username: ${DB_USERNAME:your-db-username}
    password: ${DB_PASSWORD:your-db-password}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

  logging:
    level:
      org.springframework: DEBUG
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  servlet:
    context-path: /mental-health

management:
  endpoints:
    web:
      exposure:
        include: health,info

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:your-cloudinary-cloud-name}
  api-key: ${CLOUDINARY_API_KEY:your-cloudinary-api-key}
  api-secret: ${CLOUDINARY_API_SECRET:your-cloudinary-api-secret}
  url: ${CLOUDINARY_URL:your-cloudinary-url}
