spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: mental-health
  app:
    jwtSecret: ${JWT_SECRET:your-jwt-secret}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mental_health}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:your-db-password}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

  logging:
    level:
      org.springframework: INFO
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  servlet:
    context-path: /mental-health

management:
  endpoints:
    web:
      exposure:
        include: health,info
    security:
      enabled: false
mvc:
  throw-exception-if-no-handler-found: true
cloudinary:
  cloud-name: your-cloud-name
  api-key: your-api-key
  api-secret: your-api-secret
  url: cloudinary://your-api-key:your-api-secret@your-cloud-name