spring:
  application:
    name: mental-health
  app:
    jwtSecret: 8EBUtzmOnBj56DWepYHgxuNv8rJrOYFXkqptcCzW7LVyQUV1mNhrb1UlyP1qebfk

    jwtExpirationMs: 3600000
  jpa:
    hibernate:
      ddl-auto: none  # Use migrations for production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mental_health}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:211004}

  logging:
    level:
      org.springframework: DEBUG

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

management:
  endpoints:
    web:
      exposure:
        include: health,info
